perf tool: arm-ccn: add a supplemental strerror function
Use the Arm CCN driver as an example of how to try to improve
upon its existing dmesg error output, and duplicate error string
generation logic in the perf tool.

EXAMPLE 1: Problem:  The perf tool doesn't specify to which event its generic
message applies.

BEFORE THIS PATCH:

Error: PMU Hardware doesn't support sampling/overflow-interrupts.

Adding a '-v' after the record yields the same result.

-vv shows perf_event_attr listings, but no names of events:

------------------------------------------------------------
perf_event_attr:
  type                             6
  size                             112
  config                           0x13
  { sample_period, sample_freq }   4000
  sample_type                      IP|TID|TIME|ID|PERIOD
  read_format                      ID
  disabled                         1
  inherit                          1
  mmap                             1
  comm                             1
  freq                             1
  enable_on_exec                   1
  task                             1
  sample_id_all                    1
  exclude_guest                    1
  mmap2                            1
  comm_exec                        1
------------------------------------------------------------
sys_perf_event_open: pid 21416  cpu 0  group_fd -1  flags 0x8 = 4
sys_perf_event_open: pid 21416  cpu 1  group_fd -1  flags 0x8 = 5
sys_perf_event_open: pid 21416  cpu 2  group_fd -1  flags 0x8 = 6
sys_perf_event_open: pid 21416  cpu 3  group_fd -1  flags 0x8 = 8
------------------------------------------------------------
perf_event_attr:
  type                             6
  size                             112
  config                           0x16
  { sample_period, sample_freq }   4000
  sample_type                      IP|TID|TIME|ID|PERIOD
  read_format                      ID
  disabled                         1
  inherit                          1
  freq                             1
  enable_on_exec                   1
  sample_id_all                    1
  exclude_guest                    1
------------------------------------------------------------
sys_perf_event_open: pid 21416  cpu 0  group_fd -1  flags 0x8 = 9
sys_perf_event_open: pid 21416  cpu 1  group_fd -1  flags 0x8 = 10
sys_perf_event_open: pid 21416  cpu 2  group_fd -1  flags 0x8 = 11
sys_perf_event_open: pid 21416  cpu 3  group_fd -1  flags 0x8 = 12
------------------------------------------------------------
perf_event_attr:
  type                             8
  size                             112
  config                           0xff00
  { sample_period, sample_freq }   4000
  sample_type                      IP|TID|TIME|ID|PERIOD
  read_format                      ID
  disabled                         1
  inherit                          1
  freq                             1
  enable_on_exec                   1
  sample_id_all                    1
  exclude_guest                    1
------------------------------------------------------------
sys_perf_event_open: pid -1  cpu 1  group_fd -1  flags 0x8
sys_perf_event_open failed, error -95
Error:
PMU Hardware doesn't support sampling/overflow-interrupts.

Note that the Arm CCN driver already emits its errors to dmesg, so this is what
things would look like if the user had executed 'dmesg -w &" prior to
invocation:

PMU Hardware doesn't support sampling/overflow-interrupts.

Only in that case, can the user clearly see it's the CCN event that doesn't
support sampling.

AFTER THIS PATCH:

The perf tool has been modified to say which event doesn't support sampling:

Error: ccn/cycles/: Sampling not supported, try 'perf stat' PMU Hardware
doesn't support sampling/overflow-interrupts.

EXAMPLE 2:  Problem:  stat output contains "<not supported>" for events without
explanation.

BEFORE THIS PATCH:

Warning:
ccn/cycles/ku event is not supported by the kernel.
failed to read counter ccn/cycles/ku

 Performance counter stats for 'system wide':

   <not supported>      ccn/cycles/ku

       1.002756731 seconds time elapsed

Meanwhile, dmesg contains:

[15815.248985] arm-ccn e8000000.ccn: Can't exclude execution levels!

AFTER THIS PATCH:

The tool tells the user the event can't exclude execution levels:

Warning:
ccn/cycles/ku event is not supported by the kernel.
Error:
ccn/cycles/ku: Can't exclude execution levels!
The sys_perf_event_open() syscall returned with 22 (Invalid argument) for event (ccn/cycles/ku).
/bin/dmesg may provide additional information.
No CONFIG_PERF_EVENTS=y kernel support configured?
failed to read counter ccn/cycles/ku

 Performance counter stats for 'system wide':

   <not supported>      ccn/cycles/ku

       1.002935620 seconds time elapsed

EXAMPLE 3:  Problem:  stat output contains "<not supported>" for events without
detailed explanation, to the point where the tool refers the user the driver's
output in dmesg.

BEFORE THIS PATCH:

Without -v, we just get '<not supported>' as the count.  Turning on '-v' we are
explained that it's not supported 'by the kernel' and that something 'failed to
read counter':

Warning:
ccn/xp_watchpoint,xp=3,vc=5,port=9,dir=1,cmp_l=0,cmp_h=1,mask=0/ event is not supported by the kernel.
failed to read counter ccn/xp_watchpoint,xp=3,vc=5,port=9,dir=1,cmp_l=0,cmp_h=1,mask=0/

 Performance counter stats for 'system wide':

   <not supported>      ccn/xp_watchpoint,xp=3,vc=5,port=9,dir=1,cmp_l=0,cmp_h=1,mask=0/

       1.002947707 seconds time elapsed

Meanwhile, the kernel driver has written these messages to dmesg:

[16561.854700] arm-ccn e8000000.ccn: Can't exclude execution levels!
[16561.872725] arm-ccn e8000000.ccn: Invalid vc 5 for node/XP 3!

AFTER THIS PATCH:

The driver's EINVAL condition possibilities are presented to
the user, with a note to see dmesg for the details:

Warning:
ccn/xp_watchpoint,xp=3,vc=5,port=9,dir=1,cmp_l=0,cmp_h=1,mask=0/ event is not supported by the kernel.
Error:
ccn/xp_watchpoint,xp=3,vc=5,port=9,dir=1,cmp_l=0,cmp_h=1,mask=0/: Invalid MN / XP / node ID, or node type, or node/XP port / vc or event, or mixed PMU group. See dmesg for details
The sys_perf_event_open() syscall returned with 22 (Invalid argument) for event (ccn/xp_watchpoint,xp=3,vc=5,port=9,dir=1,cmp_l=0,cmp_h=1,mask=0/).
/bin/dmesg may provide additional information.
No CONFIG_PERF_EVENTS=y kernel support configured?
failed to read counter ccn/xp_watchpoint,xp=3,vc=5,port=9,dir=1,cmp_l=0,cmp_h=1,mask=0/

 Performance counter stats for 'system wide':

   <not supported>      ccn/xp_watchpoint,xp=3,vc=5,port=9,dir=1,cmp_l=0,cmp_h=1,mask=0/

       1.002920980 seconds time elapsed

In this case, setting vc=3 worked:

 Performance counter stats for 'system wide':

                 0      ccn/xp_watchpoint,xp=3,vc=3,port=9,dir=1,cmp_l=0,cmp_h=1,mask=0/

       1.003270551 seconds time elapsed

Comments?

Signed-off-by:  Kim Phillips <kim.phillips@arm.com>