Coresight: allow to build as modules
depends on additions - select just selects, user can later deselect.  We need true dependencies written out here for module loading to work.

depends on AMBA, not select

kernel/pid.c: export find_task_by_vpid because coresight module needs it

export coresight_vpid_to_pid

coresight-stm unconditionally calls stm_register_device, it therefore DEPENDS on CONFIG_STM (select doesnt work with m anyway?)

use -objs to denote merge object directives in Makefile, -core nomenclature

add a coresight_exit() that unregisters the coresight bus

unify funnel and replicator objs into one coresight-link-sink

keep funnel and replicator separate, doubly defined init fn.

/home/kimphi01/git/linux/juno/../drivers/hwtracing/coresight/coresight-replicator.c:163: multiple definition of `init_module'
drivers/hwtracing/coresight/coresight-funnel.o:/home/kimphi01/git/linux/juno/../drivers/hwtracing/coresight/coresight-funnel.c:270: first defined here

clean up depends on clauses.  See inside for dup filename /devices/cs_etm, etm_perf_init -EEXIST due to another dup

etm-perf unregister_pmu upon exit.  Inside see CONFIG_HOTPLUG_CPU || CONFIG_KEXEC_CORE panique on shutdown

etm-perf module shoul dbe built with etm module(s)

otherwise we get it without ETM, which has no point:

BEFORE:
kernel/drivers/hwtracing/coresight/coresight-core.ko
kernel/drivers/hwtracing/coresight/coresight-cpu-debug.ko
kernel/drivers/hwtracing/coresight/coresight-etm-perf.ko
AFTER:
  INSTALL drivers/hwtracing/coresight/coresight-core.ko
  INSTALL drivers/hwtracing/coresight/coresight-cpu-debug.ko

make cpu_DEBUG depend on CORESIGHT, because of that of_coresight_get_cpu symbol dep.

root@juno:~# insmod /lib/modules/4.16.0-rc2-00115-g8d5d3bef40c3-dirty/kernel/drivers/hwtracing/coresight/coresight-cpu-debug.ko
[ 6995.043305] coresight_cpu_debug: Unknown symbol of_coresight_get_cpu (err 0)
insmod: ERROR: could not insert module /lib/modules/4.16.0-rc2-00115-g8d5d3bef40c3-dirty/kernel/drivers/hwtracing/coresight/coresight-cpu-debug.ko: Unknown symbol in module
root@juno:~# insmod /lib/modules/4.16.0-rc2-00115-g8d5d3bef40c3-dirty/kernel/drivers/hwtracing/coresight/coresight-core.ko
root@juno:~# insmod /lib/modules/4.16.0-rc2-00115-g8d5d3bef40c3-dirty/kernel/drivers/hwtracing/coresight/coresight-cpu-debug.ko
[ 7015.500212] coresight-cpu-debug 22010000.cpu-debug: Coresight debug-CPU1 initialized
[ 7015.509046] coresight-cpu-debug 22110000.cpu-debug: Coresight debug-CPU2 initialized
[ 7015.518884] coresight-cpu-debug 23010000.cpu-debug: Coresight debug-CPU0 initialized
[ 7015.527700] coresight-cpu-debug 23110000.cpu-debug: Coresight debug-CPU3 initialized
[ 7015.535528] coresight-cpu-debug 23210000.cpu-debug: Coresight debug-CPU4 initialized
[ 7015.545443] coresight-cpu-debug 23310000.cpu-debug: Coresight debug-CPU5 initialized

make coresight funnel a module, with remove()

add remove fns for most others.

fix up rest of modeulst with ID tables...need to go over __init and __exits again

merge failure: fixup remaining bools->tristates.

add MODULE_ to coresight.c for coresight_core?

add missing MODULE_*

remove dummy function defs if !CORESIGHT..builds ok