arm_spe_pmu: fix build error since rebase has new perf_aux_output_flag API
../drivers/perf/arm_spe_pmu.c: In function ‘__arm_spe_pmu_next_off’:
../drivers/perf/arm_spe_pmu.c:518:3: error: too many arguments to function ‘perf_aux_output_end’
   perf_aux_output_end(handle, 0, PERF_AUX_FLAG_TRUNCATED);
   ^
In file included from ../drivers/perf/arm_spe_pmu.c:32:0:
../include/linux/perf_event.h:852:13: note: declared here
 extern void perf_aux_output_end(struct perf_output_handle *handle,
             ^
../drivers/perf/arm_spe_pmu.c: In function ‘arm_spe_perf_aux_output_end’:
../drivers/perf/arm_spe_pmu.c:619:2: error: too many arguments to function ‘perf_aux_output_end’
  perf_aux_output_end(handle, size,
  ^
In file included from ../drivers/perf/arm_spe_pmu.c:32:0:
../include/linux/perf_event.h:852:13: note: declared here
 extern void perf_aux_output_end(struct perf_output_handle *handle,
             ^
../scripts/Makefile.build:294: recipe for target 'drivers/perf/arm_spe_pmu.o' failed
make[3]: *** [drivers/perf/arm_spe_pmu.o] Error 1
../scripts/Makefile.build:553: recipe for target 'drivers/perf' failed
make[2]: *** [drivers/perf] Error 2
make[2]: *** Waiting for unfinished jobs....