coresight: allow the coresight core code to be built as a module
Allow to build coresight as modules.  This greatly enhances developer
efficiency by allowing the development to take place exclusively on the
target, and without needing to reboot in between changes.

- Kconfig bools become tristates, to allow =m

- use -objs to denote merge object directives in Makefile, adds a
  coresight-core nomenclature for the base module.

- Export core functions so as to be able to be used by
  non-core modules.

- add a coresight_exit() that unregisters the coresight bus, add
  remove fns for most others.

- fix up modules with ID tables for autoloading on boot

modules can have only one init/exit; move coresight_init/exit into etm_perf_init/exit

make coresight core build as a module - shold be fn exports only

ERROR: "of_get_coresight_platform_data" [drivers/hwtracing/coresight/coresight-tpiu.ko] undefined!
ERROR: "of_get_coresight_platform_data" [drivers/hwtracing/coresight/coresight-tmc.ko] undefined!
ERROR: "of_get_coresight_platform_data" [drivers/hwtracing/coresight/coresight-stm.ko] undefined!
ERROR: "of_get_coresight_platform_data" [drivers/hwtracing/coresight/coresight-replicator.ko] undefined!
ERROR: "of_get_coresight_platform_data" [drivers/hwtracing/coresight/coresight-funnel.ko] undefined!
ERROR: "of_get_coresight_platform_data" [drivers/hwtracing/coresight/coresight-etm4x.ko] undefined!
ERROR: "of_get_coresight_platform_data" [drivers/hwtracing/coresight/coresight-etb10.ko] undefined!
ERROR: "of_get_coresight_platform_data" [drivers/hwtracing/coresight/coresight-dynamic-replicator.ko] undefined!
ERROR: "of_coresight_get_cpu" [drivers/hwtracing/coresight/coresight-cpu-debug.ko] undefined!
../scripts/Makefile.modpost:92: recipe for target '__modpost' failed
make[2]: *** [__modpost] Error 1
/mnt/rotational/tc2-nfs/linux/Makefile:1277: recipe for target 'modules' failed
make[1]: *** [modules] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/mnt/rotational/tc2-nfs/linux/juno'
Makefile:146: recipe for target 'sub-make' failed

all submodules use of_get_coresight_platform_data directly...glob of_coresight into the main coresight module.

lessee if really needed...Revert "make coresight core build as a module - shold be fn exports only"

This reverts commit 12f08fadef3ea2aea4e73e6aedf962d0fbd73fc6.

Cc: Mathieu Poirier <mathieu.poirier@linaro.org>
Cc: Leo Yan <leo.yan@linaro.org>
Cc: Alexander Shishkin <alexander.shishkin@linux.intel.com>
Cc: Randy Dunlap <rdunlap@infradead.org>
Cc: Suzuki K Poulose <Suzuki.Poulose@arm.com>
Cc: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Cc: Russell King <linux@armlinux.org.uk>
Signed-off-by: Kim Phillips <kim.phillips@arm.com>