Revert "coresight: no -core in Makefile"
  MODPOST 13 modules
WARNING: modpost: missing MODULE_LICENSE() in drivers/hwtracing/coresight/coresight.o
see include/linux/module.h for more information
ERROR: "coresight_register" [drivers/hwtracing/coresight/coresight-tpiu.ko] undefined!
ERROR: "coresight_timeout" [drivers/hwtracing/coresight/coresight-tpiu.ko] undefined!
ERROR: "coresight_unregister" [drivers/hwtracing/coresight/coresight-tpiu.ko] undefined!
ERROR: "coresight_register" [drivers/hwtracing/coresight/coresight-replicator.ko] undefined!
ERROR: "coresight_unregister" [drivers/hwtracing/coresight/coresight-replicator.ko] undefined!
ERROR: "barrier_pkt" [drivers/hwtracing/coresight/coresight-link-sink-tmc.ko] undefined!
ERROR: "coresight_timeout" [drivers/hwtracing/coresight/coresight-link-sink-tmc.ko] undefined!
ERROR: "coresight_unregister" [drivers/hwtracing/coresight/coresight-link-sink-tmc.ko] undefined!
ERROR: "coresight_register" [drivers/hwtracing/coresight/coresight-link-sink-tmc.ko] undefined!
ERROR: "coresight_register" [drivers/hwtracing/coresight/coresight-funnel.ko] undefined!
ERROR: "coresight_unregister" [drivers/hwtracing/coresight/coresight-funnel.ko] undefined!
ERROR: "etm4_config_trace_mode" [drivers/hwtracing/coresight/coresight-etm4x.ko] undefined!
ERROR: "coresight_vpid_to_pid" [drivers/hwtracing/coresight/coresight-etm4x.ko] undefined!
ERROR: "coresight_enable_path" [drivers/hwtracing/coresight/coresight-etm-perf.ko] undefined!
ERROR: "coresight_release_path" [drivers/hwtracing/coresight/coresight-etm-perf.ko] undefined!
ERROR: "coresight_build_path" [drivers/hwtracing/coresight/coresight-etm-perf.ko] undefined!
ERROR: "coresight_disable_path" [drivers/hwtracing/coresight/coresight-etm-perf.ko] undefined!
ERROR: "coresight_get_sink" [drivers/hwtracing/coresight/coresight-etm-perf.ko] undefined!
ERROR: "coresight_get_enabled_sink" [drivers/hwtracing/coresight/coresight-etm-perf.ko] undefined!
ERROR: "coresight_register" [drivers/hwtracing/coresight/coresight-etb10.ko] undefined!
ERROR: "coresight_timeout" [drivers/hwtracing/coresight/coresight-etb10.ko] undefined!
ERROR: "barrier_pkt" [drivers/hwtracing/coresight/coresight-etb10.ko] undefined!
ERROR: "coresight_unregister" [drivers/hwtracing/coresight/coresight-etb10.ko] undefined!
ERROR: "coresight_register" [drivers/hwtracing/coresight/coresight-dynamic-replicator.ko] undefined!
ERROR: "coresight_unregister" [drivers/hwtracing/coresight/coresight-dynamic-replicator.ko

This reverts commit 26a24617056d95609c3f9ba742becfe7cd00e32b.