BEGIN coresight (core) as module, allow
modules can have only one init/exit; move coresight_init/exit into etm_perf_init/exit

make coresight core build as a module - shold be fn exports only

ERROR: "of_get_coresight_platform_data" [drivers/hwtracing/coresight/coresight-tpiu.ko] undefined!
ERROR: "of_get_coresight_platform_data" [drivers/hwtracing/coresight/coresight-tmc.ko] undefined!
ERROR: "of_get_coresight_platform_data" [drivers/hwtracing/coresight/coresight-stm.ko] undefined!
ERROR: "of_get_coresight_platform_data" [drivers/hwtracing/coresight/coresight-replicator.ko] undefined!
ERROR: "of_get_coresight_platform_data" [drivers/hwtracing/coresight/coresight-funnel.ko] undefined!
ERROR: "of_get_coresight_platform_data" [drivers/hwtracing/coresight/coresight-etm4x.ko] undefined!
ERROR: "of_get_coresight_platform_data" [drivers/hwtracing/coresight/coresight-etb10.ko] undefined!
ERROR: "of_get_coresight_platform_data" [drivers/hwtracing/coresight/coresight-dynamic-replicator.ko] undefined!
ERROR: "of_coresight_get_cpu" [drivers/hwtracing/coresight/coresight-cpu-debug.ko] undefined!
../scripts/Makefile.modpost:92: recipe for target '__modpost' failed
make[2]: *** [__modpost] Error 1
/mnt/rotational/tc2-nfs/linux/Makefile:1277: recipe for target 'modules' failed
make[1]: *** [modules] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/mnt/rotational/tc2-nfs/linux/juno'
Makefile:146: recipe for target 'sub-make' failed

all submodules use of_get_coresight_platform_data directly...glob of_coresight into the main coresight module.

lessee if really needed...Revert "make coresight core build as a module - shold be fn exports only"

This reverts commit 12f08fadef3ea2aea4e73e6aedf962d0fbd73fc6.